export default async function handler(event, context): Promise<void> {
  try {
    
  } catch (error) {
    console.error('Error occurred in Lambda:', error);
    throw error;
  }
}
